# log-instrument - Logging instrumentation
# Depends on log-instrument-macros

rust_library(
    name = "log_instrument",
    srcs = glob(["src/**/*.rs"]),
    crate = "log_instrument",
    edition = "2024",
    deps = [
        "//third-party/rust:log",
        "//firecracker/src/log-instrument-macros:log_instrument_macros",
    ],
    visibility = ["PUBLIC"],
)
