rust_library(
    name = "event_monitor",
    srcs = glob(["src/**/*.rs"]),
    crate = "event_monitor",
    edition = "2024",
    deps = [
        "//third-party/rust:flume",
        "//third-party/rust:libc",
        "//third-party/rust:log",
        "//third-party/rust:serde",
        "//third-party/rust:serde_json",
    ],
    visibility = ["PUBLIC"],
)
