// Bridge Server Entry Point
// PureScript compiled output entry
"use strict";

// This file will be generated by PureScript compiler
// It imports the main module and runs it
require("./Bridge.Main/index.js").main();
