#!/usr/bin/env node
/**
 * Build script for OpenCode SDK
 * 
 * This script:
 * 1. Compiles PureScript SDK to JavaScript
 * 2. Generates TypeScript definitions
 * 3. Copies files to dist/
 */

const { spawn } = require("child_process");
const fs = require("fs");
const path = require("path");

const distDir = path.join(__dirname, "..", "dist");
const srcDir = path.join(__dirname, "..", "src");

async function build() {
  console.log("Building OpenCode SDK...");
  
  // Ensure dist directory exists
  if (!fs.existsSync(distDir)) {
    fs.mkdirSync(distDir, { recursive: true });
  }
  
  // Step 1: Compile PureScript to JavaScript
  console.log("Step 1: Compiling PureScript...");
  await runCommand("spago", ["build", "--purs-args", "--codegen", "js"], {
    cwd: path.join(__dirname, "..", "..", "..", "COMPASS"),
  });
  
  // Step 2: Copy compiled JS files
  console.log("Step 2: Copying compiled files...");
  const outputDir = path.join(__dirname, "..", "..", "..", "COMPASS", "output");
  if (fs.existsSync(outputDir)) {
    copyDirectory(outputDir, path.join(distDir, "output"));
  }
  
  // Step 3: Generate TypeScript definitions
  console.log("Step 3: Generating TypeScript definitions...");
  // TypeScript definitions are generated by PureScript compiler via --codegen dts
  // This step is handled by spago build with appropriate flags
  
  // Step 4: Copy source files
  console.log("Step 4: Copying source files...");
  copyFile(path.join(srcDir, "index.ts"), path.join(distDir, "index.js"));
  copyFile(path.join(srcDir, "client.ts"), path.join(distDir, "client.js"));
  copyFile(path.join(srcDir, "server.ts"), path.join(distDir, "server.js"));
  
  console.log("Build complete!");
}

function runCommand(cmd, args, options = {}) {
  return new Promise((resolve, reject) => {
    const proc = spawn(cmd, args, {
      stdio: "inherit",
      ...options,
    });
    
    proc.on("close", (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`Command failed with code ${code}`));
      }
    });
    
    proc.on("error", reject);
  });
}

function copyFile(src, dest) {
  const dir = path.dirname(dest);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.copyFileSync(src, dest);
}

function copyDirectory(src, dest) {
  if (!fs.existsSync(dest)) {
    fs.mkdirSync(dest, { recursive: true });
  }
  const entries = fs.readdirSync(src, { withFileTypes: true });
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirectory(srcPath, destPath);
    } else {
      copyFile(srcPath, destPath);
    }
  }
}

build().catch((err) => {
  console.error("Build failed:", err);
  process.exit(1);
});
