{-
Welcome to a Spago project!
You can edit this file as you like.
-}
{ name = "forge"
, dependencies =
  [ "aff"
  , "affjax"
  , "argonaut"
  , "argonaut-codecs"
  , "argonaut-core"
  , "arrays"
  , "bifunctors"
  , "console"
  , "control"
  , "datetime"
  , "effect"
  , "either"
  , "exceptions"
  , "foldable-traversable"
  , "foreign"
  , "foreign-object"
  , "http-methods"
  , "integers"
  , "js-uri"
  , "lists"
  , "maybe"
  , "media-types"
  , "newtype"
  , "node-buffer"
  , "node-child-process"
  , "node-fs"
  , "node-path"
  , "node-process"
  , "node-readline"
  , "node-streams"
  , "numbers"
  , "ordered-collections"
  , "partial"
  , "prelude"
  , "profunctor"
  , "refs"
  , "strings"
  , "tailrec"
  , "transformers"
  , "tuples"
  , "typelevel-prelude"
  , "unfoldable"
  , "uuid"
  , "web-dom"
  , "web-events"
  , "web-html"
  , "web-socket"
  , "web-storage"
  ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs" ]
}
